### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by Wing90909090** [christorange/QC-CNN#5]
Thanks you for you make this code, is very good for me understanding. 

Here:
https://pennylane.ai/qml/demos/tutorial_quantum_transfer_learning.html

```
@qml.qnode(dev, interface="torch")
def quantum_net(q_input_features, q_weights_flat):
    
    # Reshape weights
    q_weights = q_weights_flat.reshape(q_depth, n_qubits)

    # Start from state |+> , unbiased w.r.t. |0> and |1>
    H_layer(n_qubits)

    # Embed features in the quantum node
    RY_layer(q_input_features)

    # Sequence of trainable variational layers
    for k in range(q_depth):
        entangling_layer(n_qubits)
        RY_layer(q_weights[k])

    # Expectation values in the Z basis
    exp_vals = [[qml.expval](https://docs.pennylane.ai/en/stable/code/api/pennylane.expval.html#pennylane.expval)([qml.PauliZ]
```
(https://docs.pennylane.ai/en/stable/code/api/pennylane.PauliZ.html#pennylane.PauliZ)(position)) for position in range(n_qubits)]
    return tuple(exp_vals)
He make use of reshape weights, but your code no make use. Why? Whts is difference? 

Also here:
https://github.com/christorange/QC-CNN/blob/6f498d25de4187b730f7b146ad691e95520ed2d9/models/single_encoding.py#LL36C4-L42C43

```
 x_lst = []
for i in range(0, x.shape[2]-1,2):
    for j in range(0, x.shape[3]-1,2):
        x_lst.append(self.ql1(torch.flatten(x[:, :, i:i + self.kernel_size, j:j + self.kernel_size], start_dim=1)))
x = torch.cat(x_lst,dim=1)  # .view(bs,n_qubits,14,14)
```
What is the prupose of x_lst and make loop after? I no understand. 

If want make process 64x64 image, what change neem make? 

Thanks you and sorry for bad english.

**Comment by christorange** [comment]
Very detailed and well described, don't feel sorry for your English! :)

1. `q_weights_flat` is a flattened weight tensor and needs to be transformed to the desired shape with `reshape`. In our code, weights are already in shape: `weight_shapes = {"weights": (n_layers, 2 * n_qubits)}`
2. The loop implements convolution operation, since we're writing a customized layer here the convolution has to be implemented manually. `x_lst` is to store the output of convolution, then get concatenated to `X` to form the output feature map.
3. Firstly you need to change the boundary of convolution operation according to your selected kernel size and stride, then change the input of linear layer to fit the output size of QNN layer. Set `image_x_y_dim` to your image size.

**Comment by Wing90909090** [comment]
Thanks you so much, very helpful. 
More question,  here:
```
# Embed features in the quantum node
RY_layer(q_input_features)
```
They make embedd features before quantum circuit, you not make this? 

Thanks

**Comment by christorange** [comment]
The 'features' are equivalent to the 'inputs' in my code: `def circuit(inputs, weights)`. Each of my model has encoding gates, embedding and encoding are equivalent too.

**Comment by Wing90909090** [comment]
OK,
In your circuit (hubrid_layer), why make so much repetition of Rz,Ry? 
<img width="454" alt="image" src="https://github.com/christorange/QC-CNN/assets/133880228/9c57e2cd-567a-4769-b397-46f9975ecb7e">

**Comment by christorange** [comment]
It's for multiple encoding
![image](https://github.com/christorange/QC-CNN/assets/85213835/77e23e83-6c4f-4c3e-935d-17787e919e4a)

I'll deprecate `hybrid_layer.py` later, plz refer to `multi_encoding.py`
